apiVersion: fishykeys.2v.pm/v1alpha1
kind: FishySecret
metadata:
  name: test-fishy-secret
  namespace: default
spec:
  token: "dummy-token"
  server: "https://fishysecret.com"
  target:
    name: test-secret
    namespace: default
  data:
    - secretPath: "/app/db/username"
      secretKeyName: "DB_USER"
    - secretPath: "/app/db/password"
      secretKeyName: "DB_PASS"
