swagger: "2.0"
info:
    title: FishyKeys API
    description: The FishyKeys API for key management
    version: "1.0"
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /key_management/create_master_key:
        post:
            tags:
                - fishykeys
            summary: add_share fishykeys
            description: Add a share to unlock the master key
            operationId: fishykeys#add_share
            parameters:
                - name: add_share_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FishykeysAddShareRequestBody'
                    required:
                        - share
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/FishykeysAddShareResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        type: string
                "409":
                    description: Conflict response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
    /key_management/status:
        get:
            tags:
                - fishykeys
            summary: get_key_status fishykeys
            description: Get the current status of the master key
            operationId: fishykeys#get_key_status
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FishykeysGetKeyStatusResponseBody'
                        required:
                            - is_locked
                            - current_shares
                            - min_shares
                            - total_shares
                "404":
                    description: Not Found response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
definitions:
    FishykeysAddShareRequestBody:
        title: FishykeysAddShareRequestBody
        type: object
        properties:
            share:
                type: integer
                description: One of the shares need to unlock the master key
                example: 5
                format: int64
        example:
            share: 5
        required:
            - share
    FishykeysAddShareResponseBody:
        title: FishykeysAddShareResponseBody
        type: object
        properties:
            index:
                type: integer
                description: The index of the share added
                example: 3773266613403734291
                format: int64
        example:
            index: 1713451832187604687
    FishykeysCreateMasterKeyRequestBody:
        title: FishykeysCreateMasterKeyRequestBody
        type: object
        properties:
            min_shares:
                type: integer
                description: Minimum number of shares required to reconstruct the key
                example: 3
                format: int64
            total_shares:
                type: integer
                description: Total number of shares to create
                example: 5
                format: int64
        example:
            min_shares: 3
            total_shares: 5
        required:
            - total_shares
            - min_shares
    FishykeysCreateMasterKeyResponseBody:
        title: FishykeysCreateMasterKeyResponseBody
        type: object
        properties:
            shares:
                type: array
                items:
                    type: string
                    example: Quo et reprehenderit.
                description: The generated key shares
                example:
                    - Cumque et ratione autem sunt.
                    - Vitae quia enim ut.
                    - Maxime voluptas qui quia possimus.
                    - Magnam quia consequatur rem beatae a maxime.
        example:
            shares:
                - Autem voluptate occaecati minima fugiat laboriosam.
                - Dolores nesciunt occaecati neque cum.
    FishykeysGetKeyStatusResponseBody:
        title: FishykeysGetKeyStatusResponseBody
        type: object
        properties:
            current_shares:
                type: integer
                description: Number of shares currently held
                example: 1825174946653460072
                format: int64
            is_locked:
                type: boolean
                description: Whether the key is currently locked
                example: true
            min_shares:
                type: integer
                description: Minimum number of shares required
                example: 2721240584742661603
                format: int64
            total_shares:
                type: integer
                description: Total number of shares
                example: 1050104123142298514
                format: int64
        example:
            current_shares: 5011669276897181081
            is_locked: false
            min_shares: 8790618916521164378
            total_shares: 7582538673232719918
        required:
            - is_locked
            - current_shares
            - min_shares
            - total_shares
