openapi: 3.0.3
info:
    title: FishyKeys API
    description: The FishyKeys API for key management
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /key_management/create_master_key:
        post:
            tags:
                - fishykeys
            summary: add_share fishykeys
            description: Add a share to unlock the master key
            operationId: fishykeys#add_share
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddShareRequestBody'
                        example:
                            share: 5
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AddShareResponseBody'
                            example:
                                index: 3541594672439882819
                "400":
                    description: 'invalid_parameters: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ducimus et assumenda neque commodi repudiandae sit.
                            example: Saepe nesciunt aut.
                "409":
                    description: 'too_many_shares: Conflict response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Perspiciatis consectetur consequuntur quia libero vel.
                            example: Eveniet laudantium est incidunt ut.
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Consequuntur animi qui ad ratione.
                            example: Id fuga in numquam voluptatem.
    /key_management/status:
        get:
            tags:
                - fishykeys
            summary: get_key_status fishykeys
            description: Get the current status of the master key
            operationId: fishykeys#get_key_status
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetKeyStatusResponseBody'
                            example:
                                current_shares: 1634144517155123805
                                is_locked: true
                                min_shares: 6718364374947157668
                                total_shares: 7654723300438466742
                "404":
                    description: 'no_key_set: Not Found response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Rem quisquam quae sunt eos in ut.
                            example: Suscipit fuga impedit nesciunt maxime.
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Voluptas numquam aut et sed voluptatum.
                            example: Enim iure.
components:
    schemas:
        AddShareRequestBody:
            type: object
            properties:
                share:
                    type: integer
                    description: One of the shares need to unlock the master key
                    example: 5
                    format: int64
            example:
                share: 5
            required:
                - share
        AddShareResponseBody:
            type: object
            properties:
                index:
                    type: integer
                    description: The index of the share added
                    example: 552660392149742136
                    format: int64
            example:
                index: 7527884732173663858
        CreateMasterKeyRequestBody:
            type: object
            properties:
                min_shares:
                    type: integer
                    description: Minimum number of shares required to reconstruct the key
                    example: 3
                    format: int64
                total_shares:
                    type: integer
                    description: Total number of shares to create
                    example: 5
                    format: int64
            example:
                min_shares: 3
                total_shares: 5
            required:
                - total_shares
                - min_shares
        CreateMasterKeyResponseBody:
            type: object
            properties:
                shares:
                    type: array
                    items:
                        type: string
                        example: Omnis numquam voluptatem quae.
                    description: The generated key shares
                    example:
                        - Earum qui at provident repellat qui iure.
                        - Labore molestiae maxime ut dignissimos.
                        - Fugiat minima.
                        - Eum possimus.
            example:
                shares:
                    - Aut dolores.
                    - Quam voluptatem ea.
        GetKeyStatusResponseBody:
            type: object
            properties:
                current_shares:
                    type: integer
                    description: Number of shares currently held
                    example: 6597967831032783709
                    format: int64
                is_locked:
                    type: boolean
                    description: Whether the key is currently locked
                    example: false
                min_shares:
                    type: integer
                    description: Minimum number of shares required
                    example: 6553916485925491878
                    format: int64
                total_shares:
                    type: integer
                    description: Total number of shares
                    example: 5272011913761022925
                    format: int64
            example:
                current_shares: 3475276066018248154
                is_locked: true
                min_shares: 5326118618025669261
                total_shares: 6752325125503319315
            required:
                - is_locked
                - current_shares
                - min_shares
                - total_shares
tags:
    - name: fishykeys
      description: The FishyKeys server handles master key operations
