swagger: "2.0"
info:
    title: FishyKeys API
    description: The FishyKeys API for key management
    version: "1.0"
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /key_management/create_master_key:
        post:
            tags:
                - fishykeys
            summary: create_master_key fishykeys
            description: Create a new master key and split it into shares
            operationId: fishykeys#create_master_key
            parameters:
                - name: create_master_key_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FishykeysCreateMasterKeyRequestBody'
                    required:
                        - total_shares
                        - min_shares
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/FishykeysCreateMasterKeyResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        type: string
                "409":
                    description: Conflict response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
    /key_management/share:
        post:
            tags:
                - fishykeys
            summary: add_share fishykeys
            description: Add a share to unlock the master key
            operationId: fishykeys#add_share
            parameters:
                - name: add_share_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FishykeysAddShareRequestBody'
                    required:
                        - share
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/FishykeysAddShareResponseBody'
                        required:
                            - index
                            - unlocked
                "400":
                    description: Bad Request response.
                    schema:
                        type: string
                "404":
                    description: Not Found response.
                    schema:
                        type: string
                "409":
                    description: Conflict response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
        delete:
            tags:
                - fishykeys
            summary: delete_share fishykeys
            description: Delete a share from the key management system
            operationId: fishykeys#delete_share
            parameters:
                - name: delete_share_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FishykeysDeleteShareRequestBody'
                    required:
                        - index
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        type: string
                "404":
                    description: Not Found response.
                    schema:
                        type: string
                "409":
                    description: Conflict response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
    /key_management/status:
        get:
            tags:
                - fishykeys
            summary: get_key_status fishykeys
            description: Get the current status of the master key
            operationId: fishykeys#get_key_status
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FishykeysGetKeyStatusResponseBody'
                        required:
                            - is_locked
                            - current_shares
                            - min_shares
                            - total_shares
                "404":
                    description: Not Found response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
definitions:
    FishykeysAddShareRequestBody:
        title: FishykeysAddShareRequestBody
        type: object
        properties:
            share:
                type: string
                description: One of the shares need to unlock the master key
                example: EXAMPLEA5ZKwDn8Zotr3B+d+F+UzrcJ1Yhl2rU0
        example:
            share: EXAMPLEA5ZKwDn8Zotr3B+d+F+UzrcJ1Yhl2rU0
        required:
            - share
    FishykeysAddShareResponseBody:
        title: FishykeysAddShareResponseBody
        type: object
        properties:
            index:
                type: integer
                description: The index of the share added
                example: 1009166832579766622
                format: int64
            unlocked:
                type: boolean
                description: Whether the master key has been unlocked
                example: true
        example:
            index: 6662091457102477057
            unlocked: true
        required:
            - index
            - unlocked
    FishykeysCreateMasterKeyRequestBody:
        title: FishykeysCreateMasterKeyRequestBody
        type: object
        properties:
            min_shares:
                type: integer
                description: Minimum number of shares required to reconstruct the key
                example: 3
                format: int64
            total_shares:
                type: integer
                description: Total number of shares to create
                example: 5
                format: int64
        example:
            min_shares: 3
            total_shares: 5
        required:
            - total_shares
            - min_shares
    FishykeysCreateMasterKeyResponseBody:
        title: FishykeysCreateMasterKeyResponseBody
        type: object
        properties:
            shares:
                type: array
                items:
                    type: string
                    example: Est voluptatem pariatur voluptatem.
                description: The generated key shares
                example:
                    - Ratione qui itaque amet ipsum error.
                    - Et assumenda.
                    - Commodi repudiandae sit est consequuntur animi.
        example:
            shares:
                - Ratione dolorum perspiciatis consectetur.
                - Quia libero vel quod dignissimos libero.
                - Nobis praesentium non numquam maxime rem quisquam.
                - Sunt eos in ut.
    FishykeysDeleteShareRequestBody:
        title: FishykeysDeleteShareRequestBody
        type: object
        properties:
            index:
                type: integer
                description: The index of the share to delete
                example: 1
                format: int64
        example:
            index: 1
        required:
            - index
    FishykeysGetKeyStatusResponseBody:
        title: FishykeysGetKeyStatusResponseBody
        type: object
        properties:
            current_shares:
                type: integer
                description: Number of shares currently held
                example: 6518574107503557211
                format: int64
            is_locked:
                type: boolean
                description: Whether the key is currently locked
                example: false
            min_shares:
                type: integer
                description: Minimum number of shares required
                example: 5594704514197726645
                format: int64
            total_shares:
                type: integer
                description: Total number of shares
                example: 4934522018738475179
                format: int64
        example:
            current_shares: 1686211336919984919
            is_locked: true
            min_shares: 3002255462360240987
            total_shares: 9117224753253597825
        required:
            - is_locked
            - current_shares
            - min_shares
            - total_shares
